-- AlterTable
ALTER TABLE "Option" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Question" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Vote" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;
